#!/bin/bash
echo "=== STRUCTURE & CONSISTENCY ANALYSIS ==="
echo ""
echo "1. CHARSET CONSISTENCY:"
echo "   UTF-8 (uppercase): $(grep -h 'charset="UTF-8"' *.xhtml | wc -l)"
echo "   utf-8 (lowercase): $(grep -h 'charset="utf-8"' *.xhtml | wc -l)"
echo ""
echo "2. SEMANTIC HTML5 ELEMENTS:"
echo "   Files with <main>: $(grep -l '<main' *.xhtml | wc -l)/46"
echo "   Files with <section>: $(grep -l '<section' *.xhtml | wc -l)/46"
echo "   Files with <nav>: $(grep -l '<nav' *.xhtml | wc -l)/46"
echo ""
echo "3. ACCESSIBILITY:"
echo "   Files with ARIA attributes: $(grep -l 'aria-' *.xhtml | wc -l)/46"
echo "   Files with role attributes: $(grep -l 'role=' *.xhtml | wc -l)/46"
echo ""
echo "4. EPUB3 FEATURES:"
echo "   Files with epub:type: $(grep -l 'epub:type' *.xhtml | wc -l)/46"
echo "   Files with epub namespace: $(grep -l 'xmlns:epub' *.xhtml | wc -l)/46"
echo ""
echo "5. CONTENT FEATURES:"
echo "   Chapter files: $(ls *chapter*.xhtml | wc -l)"
echo "   Part dividers: $(ls *Part*.xhtml | wc -l)"
echo "   Interactive worksheets: $(grep -l 'worksheet' *.xhtml | wc -l)"
echo "   Quizzes: $(grep -l 'quiz' *.xhtml | wc -l)"
echo "   Journal pages: $(grep -l 'journal\|Journal' *.xhtml | wc -l)"
echo ""
echo "6. MEDIA REFERENCES:"
echo "   Files with images: $(grep -l '<img' *.xhtml | wc -l)"
echo "   Total image references: $(grep -oh 'src="../images/[^"]*' *.xhtml | wc -l)"
echo ""
echo "7. CSS REFERENCES:"
echo "   Files linking to fonts.css: $(grep -l 'fonts.css' *.xhtml | wc -l)"
echo "   Files linking to style.css: $(grep -l 'style.css' *.xhtml | wc -l)"
echo "   Files linking to print.css: $(grep -l 'print.css' *.xhtml | wc -l)"
